cc_library(
    name="buffer", 
    srcs = ["buffer.c"], 
    hdrs = ["buffer.h"],
    visibility = ["//src:__pkg__", "//fs:__pkg__"],
)

cc_library(
    name="logger", 
    srcs = ["logger/logger.c"], 
    hdrs = ["logger/logger.h"],
    visibility = ["//src:__pkg__", "//fs:__pkg__"],
)
